//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroctaXP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroctaXP.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celias-Bold.ttf.
        /// </summary>
        public static string AppFontBold {
            get {
                return ResourceManager.GetString("AppFontBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celias-Medium.ttf.
        /// </summary>
        public static string AppFontRegular {
            get {
                return ResourceManager.GetString("AppFontRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celias.ttf.
        /// </summary>
        public static string AppFontThin {
            get {
                return ResourceManager.GetString("AppFontThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPrimary.
        /// </summary>
        public static string ColorPrimary {
            get {
                return ResourceManager.GetString("ColorPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPrimaryDark.
        /// </summary>
        public static string ColorPrimaryDark {
            get {
                return ResourceManager.GetString("ColorPrimaryDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Button.
        /// </summary>
        public static string ImageButtonText {
            get {
                return ResourceManager.GetString("ImageButtonText", resourceCulture);
            }
        }
    }
}
