//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroctaXP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroctaXP.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celias-Bold.ttf.
        /// </summary>
        public static string AppFontBold {
            get {
                return ResourceManager.GetString("AppFontBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celias-Medium.ttf.
        /// </summary>
        public static string AppFontRegular {
            get {
                return ResourceManager.GetString("AppFontRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celias.ttf.
        /// </summary>
        public static string AppFontThin {
            get {
                return ResourceManager.GetString("AppFontThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help \ Support.
        /// </summary>
        public static string ButtonHelpSupport {
            get {
                return ResourceManager.GetString("ButtonHelpSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string ButtonOrderDetails {
            get {
                return ResourceManager.GetString("ButtonOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATE US.
        /// </summary>
        public static string ButtonRateUs {
            get {
                return ResourceManager.GetString("ButtonRateUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFER &amp; EARN.
        /// </summary>
        public static string ButtonReferEarn {
            get {
                return ResourceManager.GetString("ButtonReferEarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorGray.
        /// </summary>
        public static string ColorGray {
            get {
                return ResourceManager.GetString("ColorGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorGrayDark.
        /// </summary>
        public static string ColorGrayDark {
            get {
                return ResourceManager.GetString("ColorGrayDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPrimary.
        /// </summary>
        public static string ColorPrimary {
            get {
                return ResourceManager.GetString("ColorPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPrimaryDark.
        /// </summary>
        public static string ColorPrimaryDark {
            get {
                return ResourceManager.GetString("ColorPrimaryDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPrimaryRipple.
        /// </summary>
        public static string ColorPrimaryRipple {
            get {
                return ResourceManager.GetString("ColorPrimaryRipple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Button.
        /// </summary>
        public static string FlatButtonText {
            get {
                return ResourceManager.GetString("FlatButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Button.
        /// </summary>
        public static string ImageButtonText {
            get {
                return ResourceManager.GetString("ImageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP VERSION.
        /// </summary>
        public static string LabelAppVersion {
            get {
                return ResourceManager.GetString("LabelAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string LabelOrderNumber {
            get {
                return ResourceManager.GetString("LabelOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT ORDERS.
        /// </summary>
        public static string LabelRecentOrders {
            get {
                return ResourceManager.GetString("LabelRecentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERED.
        /// </summary>
        public static string LabelStatusDelivered {
            get {
                return ResourceManager.GetString("LabelStatusDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us, Feedback, FAQs &amp; Share.
        /// </summary>
        public static string MainMenuDescGroctaSupport {
            get {
                return ResourceManager.GetString("MainMenuDescGroctaSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Locations, Orders History, Quick Baskets &amp; Others.
        /// </summary>
        public static string MainMenuDescMyAccount {
            get {
                return ResourceManager.GetString("MainMenuDescMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocta Support.
        /// </summary>
        public static string MainMenuGroctaSupport {
            get {
                return ResourceManager.GetString("MainMenuGroctaSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MainMenuMyAccount {
            get {
                return ResourceManager.GetString("MainMenuMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserts &amp; Beverages.
        /// </summary>
        public static string ProductCategoryBeverages {
            get {
                return ResourceManager.GetString("ProductCategoryBeverages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household Cleaning.
        /// </summary>
        public static string ProductCategoryCleaning {
            get {
                return ResourceManager.GetString("ProductCategoryCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakery &amp; Cakes.
        /// </summary>
        public static string ProductCategoryConfectionary {
            get {
                return ResourceManager.GetString("ProductCategoryConfectionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dairy Products.
        /// </summary>
        public static string ProductCategoryDairy {
            get {
                return ResourceManager.GetString("ProductCategoryDairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foodgrains &amp; Pulses.
        /// </summary>
        public static string ProductCategoryFoodgrains {
            get {
                return ResourceManager.GetString("ProductCategoryFoodgrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hygiene &amp; Cosmetics.
        /// </summary>
        public static string ProductCategoryHygiene {
            get {
                return ResourceManager.GetString("ProductCategoryHygiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs &amp; Meat.
        /// </summary>
        public static string ProductCategoryMeats {
            get {
                return ResourceManager.GetString("ProductCategoryMeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edible Oils &amp; Ghee.
        /// </summary>
        public static string ProductCategoryOils {
            get {
                return ResourceManager.GetString("ProductCategoryOils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastas &amp; Noodles.
        /// </summary>
        public static string ProductCategoryPastas {
            get {
                return ResourceManager.GetString("ProductCategoryPastas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Care &amp; Foods.
        /// </summary>
        public static string ProductCategoryPetCare {
            get {
                return ResourceManager.GetString("ProductCategoryPetCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biscuits &amp; Snacks.
        /// </summary>
        public static string ProductCategorySnacks {
            get {
                return ResourceManager.GetString("ProductCategorySnacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masala &amp; Spices.
        /// </summary>
        public static string ProductCategorySpices {
            get {
                return ResourceManager.GetString("ProductCategorySpices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string SubMenuContactUs {
            get {
                return ResourceManager.GetString("SubMenuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Locations.
        /// </summary>
        public static string SubMenuDeliveryLocations {
            get {
                return ResourceManager.GetString("SubMenuDeliveryLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions (FAQs).
        /// </summary>
        public static string SubMenuFAQs {
            get {
                return ResourceManager.GetString("SubMenuFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites Groceries.
        /// </summary>
        public static string SubMenuFavoritesGroceries {
            get {
                return ResourceManager.GetString("SubMenuFavoritesGroceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback \ Review.
        /// </summary>
        public static string SubMenuFeedback {
            get {
                return ResourceManager.GetString("SubMenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        public static string SubMenuOrderHistory {
            get {
                return ResourceManager.GetString("SubMenuOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Baskets.
        /// </summary>
        public static string SubMenuQuickBaskets {
            get {
                return ResourceManager.GetString("SubMenuQuickBaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Wallet.
        /// </summary>
        public static string SubMenuRefundWallet {
            get {
                return ResourceManager.GetString("SubMenuRefundWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share App.
        /// </summary>
        public static string SubMenuShareApp {
            get {
                return ResourceManager.GetString("SubMenuShareApp", resourceCulture);
            }
        }
    }
}
